### ISSUE TITLE
Minimize to tray

### ISSUE THREAD

**Issue by mh166** [mawie81/whatsdesktop#2]
Hi,

thank you for this very nice and easy to use GUI. :smiley:

I'm wondering if it's possible to have it stay just within the systray/notification area. This would avoid cluttering the taskbar while still having it right at hand when needed.

Maybe you can add to modes for this, that one can check in some kind of settings menu:
- Minimize to tray
- Close to tray

Thank you!

**Comment by mawie81** [comment]
Thanks for the suggestion.
I´ll try to look into it in the next couple of days :)

**Comment by mawie81** [comment]
New release is out :smiley:

**Comment by mh166** [comment]
Working like charm! Thanks for your quick response. :+1:

**Comment by KottV** [comment]
Any chances for Linux?
